import Pickup from '../models/Pickup.js';
import socketService from '../services/socketService.js';

// Generate QR code for pickup (called when pickup is assigned)
export const generatePickupQR = async (req, res) => {
    try {
        const { pickupId } = req.params;
        
        const pickup = await Pickup.findById(pickupId)
            .populate('citizen', 'name email')
            .populate('wasteItem', 'material weight');
        
        if (!pickup) {
            return res.status(404).json({
                success: false,
                message: 'Pickup not found'
            });
        }
        
        // Only allow QR generation for assigned pickups
        if (pickup.status !== 'Assigned') {
            return res.status(400).json({
                success: false,
                message: 'QR code can only be generated for assigned pickups'
            });
        }
        
        // QR code should already be generated by the pre-save hook
        if (!pickup.qrCode || !pickup.qrCodeImage) {
            return res.status(500).json({
                success: false,
                message: 'Failed to generate QR code'
            });
        }
        
        res.json({
            success: true,
            data: {
                pickupId: pickup._id,
                qrCode: pickup.qrCode,
                qrCodeImage: pickup.qrCodeImage,
                pickup: {
                    citizen: pickup.citizen.name,
                    wasteType: pickup.wasteItem.material,
                    weight: pickup.wasteItem.weight,
                    address: pickup.address,
                    scheduledDate: pickup.scheduledDate,
                    timeSlot: pickup.timeSlot
                }
            }
        });
    } catch (error) {
        console.error('Generate pickup QR error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to generate QR code',
            error: error.message
        });
    }
};

// Verify QR code (collector scans QR code)
export const verifyQRCode = async (req, res) => {
    try {
        const { qrCode } = req.body;
        const collectorId = req.user.id;
        
        if (!qrCode) {
            return res.status(400).json({
                success: false,
                message: 'QR code is required'
            });
        }
        
        // Find pickup by QR code
        const pickup = await Pickup.findByQRCode(qrCode);
        
        if (!pickup) {
            return res.status(404).json({
                success: false,
                message: 'Invalid QR code or pickup not found'
            });
        }
        
        // Verify that the collector is assigned to this pickup
        if (pickup.assignedCollector && pickup.assignedCollector._id.toString() !== collectorId) {
            return res.status(403).json({
                success: false,
                message: 'You are not assigned to this pickup'
            });
        }
        
        // Verify QR code
        const verificationResult = pickup.verifyQRCode(qrCode, collectorId);
        
        if (!verificationResult.success) {
            return res.status(400).json({
                success: false,
                message: verificationResult.message
            });
        }
        
        // Save the pickup
        await pickup.save();
        
        // Send real-time update to citizen
        socketService.emitPickupStatusUpdate(pickup._id.toString(), {
            pickupId: pickup._id,
            status: pickup.status,
            qrVerified: pickup.qrVerified,
            qrVerifiedAt: pickup.qrVerifiedAt,
            message: 'Collector has arrived and verified the pickup'
        });
        
        // Send notification to citizen
        socketService.sendNotification(pickup.citizen._id.toString(), {
            type: 'pickup_verified',
            title: 'Pickup Verified',
            message: 'Your collector has arrived and verified the pickup. Collection is now in progress.',
            data: {
                pickupId: pickup._id,
                collectorName: req.user.name,
                verifiedAt: pickup.qrVerifiedAt
            }
        });
        
        res.json({
            success: true,
            message: 'QR code verified successfully',
            data: {
                pickup: {
                    _id: pickup._id,
                    status: pickup.status,
                    qrVerified: pickup.qrVerified,
                    qrVerifiedAt: pickup.qrVerifiedAt,
                    citizen: pickup.citizen,
                    wasteItem: pickup.wasteItem,
                    address: pickup.address
                }
            }
        });
    } catch (error) {
        console.error('Verify QR code error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to verify QR code',
            error: error.message
        });
    }
};

// Complete pickup after QR verification
export const completePickup = async (req, res) => {
    try {
        const { pickupId } = req.params;
        const { actualWeight, notes, photos } = req.body;
        const collectorId = req.user.id;
        
        const pickup = await Pickup.findById(pickupId)
            .populate('citizen', 'name email')
            .populate('wasteItem', 'material weight');
        
        if (!pickup) {
            return res.status(404).json({
                success: false,
                message: 'Pickup not found'
            });
        }
        
        // Verify collector is assigned to this pickup
        if (pickup.assignedCollector && pickup.assignedCollector.toString() !== collectorId) {
            return res.status(403).json({
                success: false,
                message: 'You are not assigned to this pickup'
            });
        }
        
        // Complete the pickup
        const completionResult = pickup.completePickup(collectorId, {
            actualWeight: parseFloat(actualWeight),
            notes,
            photos: photos || []
        });
        
        if (!completionResult.success) {
            return res.status(400).json({
                success: false,
                message: completionResult.message
            });
        }
        
        // Save the pickup
        await pickup.save();
        
        // Update the waste item status
        if (pickup.wasteItem) {
            pickup.wasteItem.status = 'Collected';
            pickup.wasteItem.collector = collectorId;
            await pickup.wasteItem.save();
        }
        
        // Send real-time update to citizen
        socketService.emitPickupStatusUpdate(pickup._id.toString(), {
            pickupId: pickup._id,
            status: pickup.status,
            completedAt: pickup.completedAt,
            actualWeight: pickup.actualWeight,
            message: 'Your pickup has been completed successfully'
        });
        
        // Send notification to citizen
        socketService.sendNotification(pickup.citizen._id.toString(), {
            type: 'pickup_completed',
            title: 'Pickup Completed!',
            message: `Your waste pickup has been completed. Actual weight: ${pickup.actualWeight}kg`,
            data: {
                pickupId: pickup._id,
                actualWeight: pickup.actualWeight,
                completedAt: pickup.completedAt,
                collectorName: req.user.name
            }
        });
        
        res.json({
            success: true,
            message: 'Pickup completed successfully',
            data: {
                pickup: {
                    _id: pickup._id,
                    status: pickup.status,
                    completedAt: pickup.completedAt,
                    actualWeight: pickup.actualWeight,
                    collectionNotes: pickup.collectionNotes
                }
            }
        });
    } catch (error) {
        console.error('Complete pickup error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to complete pickup',
            error: error.message
        });
    }
};

// Get pickup details by QR code (for verification)
export const getPickupByQR = async (req, res) => {
    try {
        const { qrCode } = req.params;
        
        const pickup = await Pickup.findByQRCode(qrCode);
        
        if (!pickup) {
            return res.status(404).json({
                success: false,
                message: 'Pickup not found'
            });
        }
        
        res.json({
            success: true,
            data: {
                pickup: {
                    _id: pickup._id,
                    status: pickup.status,
                    qrVerified: pickup.qrVerified,
                    citizen: pickup.citizen,
                    wasteItem: pickup.wasteItem,
                    address: pickup.address,
                    scheduledDate: pickup.scheduledDate,
                    timeSlot: pickup.timeSlot,
                    assignedCollector: pickup.assignedCollector
                }
            }
        });
    } catch (error) {
        console.error('Get pickup by QR error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to retrieve pickup details',
            error: error.message
        });
    }
};

// Get QR verification history (admin function)
export const getQRVerificationHistory = async (req, res) => {
    try {
        const { page = 1, limit = 20, status, collectorId } = req.query;
        
        const pageNum = parseInt(page);
        const limitNum = parseInt(limit);
        const skip = (pageNum - 1) * limitNum;
        
        const query = { qrCode: { $exists: true, $ne: null } };
        if (status) query.status = status;
        if (collectorId) query.qrVerifiedBy = collectorId;
        
        const pickups = await Pickup.find(query)
            .populate('citizen', 'name email')
            .populate('wasteItem', 'material weight')
            .populate('qrVerifiedBy', 'name email')
            .populate('assignedCollector', 'name email')
            .sort({ qrVerifiedAt: -1, createdAt: -1 })
            .skip(skip)
            .limit(limitNum);
        
        const total = await Pickup.countDocuments(query);
        
        res.json({
            success: true,
            data: {
                pickups,
                pagination: {
                    currentPage: pageNum,
                    totalPages: Math.ceil(total / limitNum),
                    totalItems: total,
                    hasNext: skip + limitNum < total,
                    hasPrev: pageNum > 1
                }
            }
        });
    } catch (error) {
        console.error('Get QR verification history error:', error);
        res.status(500).json({
            success: false,
            message: 'Failed to retrieve verification history',
            error: error.message
        });
    }
};